[package]
name = "shticker_book_unwritten"
version = "1.0.5"
authors = ["Dr. Jonathan Helianthicus Doe, IV <augiii@protonmail.com>"]
edition = "2021"
description = "Minimal CLI launcher for the Toontown Rewritten MMORPG"
repository = """
https://github.com/JonathanHelianthicusDoe/shticker_book_unwritten"""
readme = "README.md"
keywords = ["cli", "launcher", "ttr", "toontown", "rewritten"]
categories = ["games"]
license = "GPL-3.0-or-later"

[dependencies]
bzip2 = "0.4.3"
rpassword = "6.0.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sha-1 = "0.10.0"

[dependencies.clap]
version = "3.1.18"
default-features = false
features = ["std", "cargo", "suggestions"]

[dependencies.reqwest]
version = "0.11.10"
features = ["blocking", "default-tls"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
