[package]
name = "shticker_book_unwritten"
version = "1.0.3"
authors = ["Dr. Jonathan Helianthicus Doe, IV <augiii@protonmail.com>"]
edition = "2018"
description = "Minimal CLI launcher for the Toontown Rewritten MMORPG"
repository = """
https://github.com/JonathanHelianthicusDoe/shticker_book_unwritten"""
readme = "README.md"
keywords = ["cli", "launcher", "ttr", "toontown", "rewritten"]
categories = ["games"]
license = "GPL-3.0-or-later"

[dependencies]
bzip2 = "0.4.1"
rpassword = "4.0.5"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
sha-1 = "0.9.1"

[dependencies.clap]
version = "2.33.2"
default-features = false
features = ["suggestions", "vec_map"]

[dependencies.reqwest]
version = "0.10.7"
features = ["blocking", "default-tls"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
